/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;
import Classes.Company;
import javax.swing.*;
import java.io.File;
import java.io.PrintWriter;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author andresrivas
 */
public class Interfaz extends javax.swing.JFrame {
    static Company apple;
    static Company hp;
    /**
     * Creates new form Interfaz
     */
    public Interfaz(Company apple, Company hp, int[] initialQuantitiesApple, int[] initialQuantitiesHp) {
        initComponents();
        this.apple = apple;
        this.hp = hp;
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); // Centrar la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        removeMB2 = new javax.swing.JButton();
        addMb2 = new javax.swing.JButton();
        motherBoardMakersApple = new javax.swing.JLabel();
        removeCpu1 = new javax.swing.JButton();
        cpuMakersApple = new javax.swing.JLabel();
        addCpu1 = new javax.swing.JButton();
        removeRam1 = new javax.swing.JButton();
        ramMakersApple = new javax.swing.JLabel();
        addRam1 = new javax.swing.JButton();
        removePowSour1 = new javax.swing.JButton();
        powerSourceMakersApple = new javax.swing.JLabel();
        addPowSour1 = new javax.swing.JButton();
        removeGraphCard1 = new javax.swing.JButton();
        graphCardMakersApple = new javax.swing.JLabel();
        addGraphCard1 = new javax.swing.JButton();
        removeAssembler1 = new javax.swing.JButton();
        assemblersApple = new javax.swing.JLabel();
        addAssembler1 = new javax.swing.JButton();
        removeDay = new javax.swing.JButton();
        day = new javax.swing.JLabel();
        addDay = new javax.swing.JButton();
        removeDeadline = new javax.swing.JButton();
        deadline = new javax.swing.JLabel();
        addDeadline = new javax.swing.JButton();
        removeCpu2 = new javax.swing.JButton();
        motherBoardMakersHp = new javax.swing.JLabel();
        addMotherBoard1 = new javax.swing.JButton();
        removeMotherBoard1 = new javax.swing.JButton();
        cpuMakersHp = new javax.swing.JLabel();
        addCpu2 = new javax.swing.JButton();
        removeRam2 = new javax.swing.JButton();
        ramMakersHp = new javax.swing.JLabel();
        addRam2 = new javax.swing.JButton();
        removePowSour2 = new javax.swing.JButton();
        powerSourceMakersHp = new javax.swing.JLabel();
        addPowSour2 = new javax.swing.JButton();
        removeGraphCard2 = new javax.swing.JButton();
        graphCardMakersHp = new javax.swing.JLabel();
        addGraphCard2 = new javax.swing.JButton();
        removeAssembler2 = new javax.swing.JButton();
        assemblersHp = new javax.swing.JLabel();
        addAssembler2 = new javax.swing.JButton();
        txt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        removeMB3 = new javax.swing.JButton();
        motherBoardMakersApple1 = new javax.swing.JLabel();
        addMb3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        removeCpu3 = new javax.swing.JButton();
        cpuMakersApple1 = new javax.swing.JLabel();
        addCpu3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        removeRam3 = new javax.swing.JButton();
        powerSourceMakersApple1 = new javax.swing.JLabel();
        addRam3 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        removePowSour3 = new javax.swing.JButton();
        powerSourceMakersApple2 = new javax.swing.JLabel();
        addPowSour3 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("CONFIGURACION");

        jLabel2.setText("APPLE");

        jLabel3.setText("HP");

        jLabel4.setText("Productores Placa Base:");

        jLabel5.setText("Productores de CPU:");

        jLabel6.setText("Productores de memoria RAM:");

        jLabel7.setText("Productores de Fuente de Alimentacion:");

        jLabel8.setText("Productores de Tarjetas Graficas:");

        jLabel9.setText("Ensambladores:");

        jLabel10.setText("Productores Placa Base:");

        jLabel11.setText("Productores de CPU:");

        jLabel12.setText("Productores de memoria RAM:");

        jLabel13.setText("Productores de Fuente de Alimentacion:");

        jLabel14.setText("Productores de Tarjetas Graficas:");

        jLabel15.setText("Ensambladores:");

        jLabel16.setText("Duracion del dia:");

        jLabel17.setText("Deadline:");

        removeMB2.setText("-");
        removeMB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMB2ActionPerformed(evt);
            }
        });

        addMb2.setText("+");
        addMb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMb2ActionPerformed(evt);
            }
        });

        motherBoardMakersApple.setText("0");

        removeCpu1.setText("-");
        removeCpu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCpu1ActionPerformed(evt);
            }
        });

        cpuMakersApple.setText("0");

        addCpu1.setText("+");
        addCpu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCpu1ActionPerformed(evt);
            }
        });

        removeRam1.setText("-");
        removeRam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRam1ActionPerformed(evt);
            }
        });

        ramMakersApple.setText("0");

        addRam1.setText("+");
        addRam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRam1ActionPerformed(evt);
            }
        });

        removePowSour1.setText("-");
        removePowSour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePowSour1ActionPerformed(evt);
            }
        });

        powerSourceMakersApple.setText("0");

        addPowSour1.setText("+");
        addPowSour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPowSour1ActionPerformed(evt);
            }
        });

        removeGraphCard1.setText("-");
        removeGraphCard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeGraphCard1ActionPerformed(evt);
            }
        });

        graphCardMakersApple.setText("0");

        addGraphCard1.setText("+");
        addGraphCard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGraphCard1ActionPerformed(evt);
            }
        });

        removeAssembler1.setText("-");
        removeAssembler1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAssembler1ActionPerformed(evt);
            }
        });

        assemblersApple.setText("0");

        addAssembler1.setText("+");
        addAssembler1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAssembler1ActionPerformed(evt);
            }
        });

        removeDay.setText("-");
        removeDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDayActionPerformed(evt);
            }
        });

        day.setText("0");

        addDay.setText("+");
        addDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDayActionPerformed(evt);
            }
        });

        removeDeadline.setText("-");
        removeDeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDeadlineActionPerformed(evt);
            }
        });

        deadline.setText("0");

        addDeadline.setText("+");
        addDeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDeadlineActionPerformed(evt);
            }
        });

        removeCpu2.setText("-");
        removeCpu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCpu2ActionPerformed(evt);
            }
        });

        motherBoardMakersHp.setText("0");

        addMotherBoard1.setText("+");
        addMotherBoard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMotherBoard1ActionPerformed(evt);
            }
        });

        removeMotherBoard1.setText("-");
        removeMotherBoard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMotherBoard1ActionPerformed(evt);
            }
        });

        cpuMakersHp.setText("0");

        addCpu2.setText("+");
        addCpu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCpu2ActionPerformed(evt);
            }
        });

        removeRam2.setText("-");
        removeRam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRam2ActionPerformed(evt);
            }
        });

        ramMakersHp.setText("0");

        addRam2.setText("+");
        addRam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRam2ActionPerformed(evt);
            }
        });

        removePowSour2.setText("-");
        removePowSour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePowSour2ActionPerformed(evt);
            }
        });

        powerSourceMakersHp.setText("0");

        addPowSour2.setText("+");
        addPowSour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPowSour2ActionPerformed(evt);
            }
        });

        removeGraphCard2.setText("-");
        removeGraphCard2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeGraphCard2ActionPerformed(evt);
            }
        });

        graphCardMakersHp.setText("0");

        addGraphCard2.setText("+");
        addGraphCard2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGraphCard2ActionPerformed(evt);
            }
        });

        removeAssembler2.setText("-");
        removeAssembler2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAssembler2ActionPerformed(evt);
            }
        });

        assemblersHp.setText("0");

        addAssembler2.setText("+");
        addAssembler2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAssembler2ActionPerformed(evt);
            }
        });

        txt.setText("Guardar");
        txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeAssembler1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(assemblersApple)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addAssembler1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeGraphCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(graphCardMakersApple)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addGraphCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeCpu1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpuMakersApple)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addCpu1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(removeMB2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6))
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(motherBoardMakersApple)
                                                .addGap(18, 18, 18)
                                                .addComponent(addMb2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(removeRam1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ramMakersApple)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(removePowSour1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(powerSourceMakersApple)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addPowSour1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(addRam1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel1)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeGraphCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(graphCardMakersHp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addGraphCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeCpu2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpuMakersHp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addCpu2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeAssembler2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(assemblersHp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addAssembler2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(removeMotherBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(motherBoardMakersHp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addMotherBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeRam2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ramMakersHp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addRam2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removePowSour2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(powerSourceMakersHp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addPowSour2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(removeDay, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(day)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addDay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(removeDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deadline)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(81, 81, 81))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt)
                .addGap(358, 358, 358))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(removeMB2)
                    .addComponent(addMb2)
                    .addComponent(motherBoardMakersApple)
                    .addComponent(motherBoardMakersHp)
                    .addComponent(addMotherBoard1)
                    .addComponent(removeMotherBoard1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(removeCpu1)
                    .addComponent(cpuMakersApple)
                    .addComponent(addCpu1)
                    .addComponent(removeCpu2)
                    .addComponent(cpuMakersHp)
                    .addComponent(addCpu2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(removeRam1)
                    .addComponent(ramMakersApple)
                    .addComponent(addRam1)
                    .addComponent(removeRam2)
                    .addComponent(ramMakersHp)
                    .addComponent(addRam2))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13)
                    .addComponent(removePowSour1)
                    .addComponent(powerSourceMakersApple)
                    .addComponent(addPowSour1)
                    .addComponent(removePowSour2)
                    .addComponent(powerSourceMakersHp)
                    .addComponent(addPowSour2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14)
                    .addComponent(removeGraphCard1)
                    .addComponent(graphCardMakersApple)
                    .addComponent(addGraphCard1)
                    .addComponent(removeGraphCard2)
                    .addComponent(graphCardMakersHp)
                    .addComponent(addGraphCard2))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel15)
                    .addComponent(removeAssembler1)
                    .addComponent(assemblersApple)
                    .addComponent(addAssembler1)
                    .addComponent(removeAssembler2)
                    .addComponent(assemblersHp)
                    .addComponent(addAssembler2))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(removeDay)
                    .addComponent(day)
                    .addComponent(addDay))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(removeDeadline)
                    .addComponent(deadline)
                    .addComponent(addDeadline))
                .addGap(18, 18, 18)
                .addComponent(txt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Configuration", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel38.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel38.setText("APPLE");

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("TRABAJADORES");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Productores Placa Base:");

        removeMB3.setText("-");
        removeMB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMB3ActionPerformed(evt);
            }
        });

        motherBoardMakersApple1.setForeground(new java.awt.Color(255, 255, 255));
        motherBoardMakersApple1.setText("0");

        addMb3.setText("+");
        addMb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMb3ActionPerformed(evt);
            }
        });

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Productores de CPU:");

        removeCpu3.setText("-");
        removeCpu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCpu3ActionPerformed(evt);
            }
        });

        cpuMakersApple1.setForeground(new java.awt.Color(255, 255, 255));
        cpuMakersApple1.setText("0");

        addCpu3.setText("+");
        addCpu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCpu3ActionPerformed(evt);
            }
        });

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Productores de memoria RAM:");

        removeRam3.setText("-");
        removeRam3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRam3ActionPerformed(evt);
            }
        });

        powerSourceMakersApple1.setForeground(new java.awt.Color(255, 255, 255));
        powerSourceMakersApple1.setText("0");

        addRam3.setText("+");
        addRam3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRam3ActionPerformed(evt);
            }
        });

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Productores de Fuente de Alimentacion:");

        removePowSour3.setText("-");
        removePowSour3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePowSour3ActionPerformed(evt);
            }
        });

        powerSourceMakersApple2.setForeground(new java.awt.Color(255, 255, 255));
        powerSourceMakersApple2.setText("0");

        addPowSour3.setText("+");
        addPowSour3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPowSour3ActionPerformed(evt);
            }
        });

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Productores de Tarjetas Graficas:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel18))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeMB3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(motherBoardMakersApple1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addMb3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeCpu3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cpuMakersApple1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addCpu3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeRam3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(powerSourceMakersApple1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addRam3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removePowSour3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(powerSourceMakersApple2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addPowSour3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(removeMB3)
                    .addComponent(motherBoardMakersApple1)
                    .addComponent(addMb3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(removeCpu3)
                    .addComponent(cpuMakersApple1)
                    .addComponent(addCpu3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(removeRam3)
                    .addComponent(powerSourceMakersApple1)
                    .addComponent(addRam3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(removePowSour3)
                    .addComponent(powerSourceMakersApple2)
                    .addComponent(addPowSour3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                .addComponent(jLabel38)
                .addGap(73, 73, 73))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(jLabel38)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Apple", jPanel2);

        jLabel45.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel45.setText("HP");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(693, 693, 693)
                .addComponent(jLabel45)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel45)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hp", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 816, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Apple vs Hp", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeMB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMB2ActionPerformed
        if (Integer.parseInt(motherBoardMakersApple.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(motherBoardMakersApple.getText())-1;
            motherBoardMakersApple.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeMB2ActionPerformed

    private void addMb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMb2ActionPerformed
        if (calculateQuantityApple() == 12){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(motherBoardMakersApple.getText())+1;
            motherBoardMakersApple.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addMb2ActionPerformed

    private void removeCpu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCpu1ActionPerformed
        if (Integer.parseInt(cpuMakersApple.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(cpuMakersApple.getText())-1;
            cpuMakersApple.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeCpu1ActionPerformed

    private void addCpu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCpu1ActionPerformed
        if (calculateQuantityApple() == 12){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(cpuMakersApple.getText())+1;
            cpuMakersApple.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addCpu1ActionPerformed

    private void removeRam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRam1ActionPerformed
        if (Integer.parseInt(ramMakersApple.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(ramMakersApple.getText())-1;
            ramMakersApple.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeRam1ActionPerformed

    private void addRam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRam1ActionPerformed
        if (calculateQuantityApple() == 12){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(ramMakersApple.getText())+1;
            ramMakersApple.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addRam1ActionPerformed

    private void removePowSour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePowSour1ActionPerformed
        if (Integer.parseInt(powerSourceMakersApple.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(powerSourceMakersApple.getText())-1;
            powerSourceMakersApple.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removePowSour1ActionPerformed

    private void addPowSour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPowSour1ActionPerformed
        if (calculateQuantityApple() == 12){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(powerSourceMakersApple.getText())+1;
            powerSourceMakersApple.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addPowSour1ActionPerformed

    private void removeGraphCard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeGraphCard1ActionPerformed
        if (Integer.parseInt(graphCardMakersApple.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(graphCardMakersApple.getText())-1;
            graphCardMakersApple.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeGraphCard1ActionPerformed

    private void addGraphCard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGraphCard1ActionPerformed
        if (calculateQuantityApple() == 12){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(graphCardMakersApple.getText())+1;
            graphCardMakersApple.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addGraphCard1ActionPerformed

    private void removeAssembler1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAssembler1ActionPerformed
        if (Integer.parseInt(assemblersApple.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(assemblersApple.getText())-1;
            assemblersApple.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeAssembler1ActionPerformed

    private void addAssembler1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAssembler1ActionPerformed
        if (calculateQuantityApple() == 12){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(assemblersApple.getText())+1;
            assemblersApple.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addAssembler1ActionPerformed

    private void removeDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDayActionPerformed
        if(Integer.parseInt(day.getText())==2000){
            JOptionPane.showMessageDialog(null, "EL DIA DEBE DURAR MINIMO 2000MS");
        } else {
            int nuevo = Integer.parseInt(day.getText())-1000;
            day.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeDayActionPerformed

    private void addDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDayActionPerformed
        int nuevo = Integer.parseInt(day.getText())+1000;
        day.setText(String.valueOf(nuevo));
    }//GEN-LAST:event_addDayActionPerformed

    private void removeDeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDeadlineActionPerformed
        if(Integer.parseInt(deadline.getText())== 1){
            JOptionPane.showMessageDialog(null, "SE DEBE TENER POR LO MENOS UN DIA COMO DEADLINE DE ENTREGA");
        } else {
            int nuevo = Integer.parseInt(deadline.getText())-1;
            deadline.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeDeadlineActionPerformed

    private void addDeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDeadlineActionPerformed
        int nuevo = Integer.parseInt(deadline.getText())+1;
        deadline.setText(String.valueOf(nuevo));
    }//GEN-LAST:event_addDeadlineActionPerformed

    private void removeCpu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCpu2ActionPerformed
        if (Integer.parseInt(cpuMakersHp.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(cpuMakersHp.getText())-1;
            cpuMakersHp.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeCpu2ActionPerformed

    private void addMotherBoard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMotherBoard1ActionPerformed
        if (calculateQuantityHp() == 12){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(motherBoardMakersHp.getText())+1;
            motherBoardMakersHp.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addMotherBoard1ActionPerformed

    private void removeMotherBoard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMotherBoard1ActionPerformed
        if (Integer.parseInt(motherBoardMakersHp.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(motherBoardMakersHp.getText())-1;
            motherBoardMakersHp.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeMotherBoard1ActionPerformed

    private void addCpu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCpu2ActionPerformed
        if (calculateQuantityHp() == 12){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(cpuMakersHp.getText())+1;
            cpuMakersHp.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addCpu2ActionPerformed

    private void removeRam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRam2ActionPerformed
        if (Integer.parseInt(ramMakersHp.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(ramMakersHp.getText())-1;
            ramMakersHp.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeRam2ActionPerformed

    private void addRam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRam2ActionPerformed
        if (calculateQuantityHp() == 12){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(ramMakersHp.getText())+1;
            ramMakersHp.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addRam2ActionPerformed

    private void removePowSour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePowSour2ActionPerformed
        if (Integer.parseInt(powerSourceMakersHp.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(powerSourceMakersHp.getText())-1;
            powerSourceMakersHp.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removePowSour2ActionPerformed

    private void addPowSour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPowSour2ActionPerformed
        if (calculateQuantityHp() == 12){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(powerSourceMakersHp.getText())+1;
            powerSourceMakersHp.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addPowSour2ActionPerformed

    private void removeGraphCard2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeGraphCard2ActionPerformed
        if (Integer.parseInt(graphCardMakersHp.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(graphCardMakersHp.getText())-1;
            graphCardMakersHp.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeGraphCard2ActionPerformed

    private void addGraphCard2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGraphCard2ActionPerformed
        if (calculateQuantityHp() == 12){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(graphCardMakersHp.getText())+1;
            graphCardMakersHp.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addGraphCard2ActionPerformed

    private void removeAssembler2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAssembler2ActionPerformed
        if (Integer.parseInt(assemblersHp.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(assemblersHp.getText())-1;
            assemblersHp.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeAssembler2ActionPerformed

    private void addAssembler2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAssembler2ActionPerformed
        if (calculateQuantityHp() == 12){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(assemblersHp.getText())+1;
            assemblersHp.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addAssembler2ActionPerformed

    private void txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActionPerformed
        String quantities = motherBoardMakersApple.getText() + ", " + cpuMakersApple.getText() + ", " + ramMakersApple.getText() + ", " + powerSourceMakersApple.getText() + ", " + graphCardMakersApple.getText() + ", " + assemblersApple.getText() + " / " + motherBoardMakersHp.getText() + ", " + cpuMakersHp.getText() + ", " + ramMakersHp.getText() + ", " + powerSourceMakersHp.getText() + ", " + graphCardMakersHp.getText() + ", " + assemblersHp.getText();
        String data = day.getText() + " / " + deadline.getText();

        // DATOS INICIALES
        File fichero = new File("DatosIniciales.txt");
        String contenido = "";

        try{
            PrintWriter salida = new PrintWriter(fichero);
            salida.print(data);
            salida.close();
        }catch(Exception e){
            System.out.println(e);
        }

        // CANTIDADES INICIALES

        fichero = new File("InitialQuantity.txt");

        try{
            PrintWriter salida = new PrintWriter(fichero);
            salida.print(quantities);
            salida.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_txtActionPerformed

    private void removeMB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeMB3ActionPerformed

    private void addMb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMb3ActionPerformed

    private void removeCpu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCpu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeCpu3ActionPerformed

    private void addCpu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCpu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCpu3ActionPerformed

    private void removeRam3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRam3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeRam3ActionPerformed

    private void addRam3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRam3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addRam3ActionPerformed

    private void removePowSour3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePowSour3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removePowSour3ActionPerformed

    private void addPowSour3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPowSour3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPowSour3ActionPerformed

    private int calculateQuantityApple(){
        int cantidadTotal = Integer.parseInt(motherBoardMakersApple.getText()) + Integer.parseInt(cpuMakersApple.getText()) + Integer.parseInt(ramMakersApple.getText()) + Integer.parseInt(powerSourceMakersApple.getText()) + Integer.parseInt(graphCardMakersApple.getText()) + Integer.parseInt(assemblersApple.getText());
        System.out.println(cantidadTotal);
        return cantidadTotal;
    }
    
    private int calculateQuantityHp(){
        int cantidadTotal = Integer.parseInt(motherBoardMakersHp.getText()) + Integer.parseInt(cpuMakersHp.getText()) + Integer.parseInt(ramMakersHp.getText()) + Integer.parseInt(powerSourceMakersHp.getText()) + Integer.parseInt(graphCardMakersHp.getText()) + Integer.parseInt(assemblersHp.getText());
        return cantidadTotal;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
       //         new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAssembler1;
    private javax.swing.JButton addAssembler2;
    private javax.swing.JButton addCpu1;
    private javax.swing.JButton addCpu2;
    private javax.swing.JButton addCpu3;
    private javax.swing.JButton addDay;
    private javax.swing.JButton addDeadline;
    private javax.swing.JButton addGraphCard1;
    private javax.swing.JButton addGraphCard2;
    private javax.swing.JButton addMb2;
    private javax.swing.JButton addMb3;
    private javax.swing.JButton addMotherBoard1;
    private javax.swing.JButton addPowSour1;
    private javax.swing.JButton addPowSour2;
    private javax.swing.JButton addPowSour3;
    private javax.swing.JButton addRam1;
    private javax.swing.JButton addRam2;
    private javax.swing.JButton addRam3;
    private javax.swing.JLabel assemblersApple;
    private javax.swing.JLabel assemblersHp;
    private javax.swing.JLabel cpuMakersApple;
    private javax.swing.JLabel cpuMakersApple1;
    private javax.swing.JLabel cpuMakersHp;
    private javax.swing.JLabel day;
    private javax.swing.JLabel deadline;
    private javax.swing.JLabel graphCardMakersApple;
    private javax.swing.JLabel graphCardMakersHp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel motherBoardMakersApple;
    private javax.swing.JLabel motherBoardMakersApple1;
    private javax.swing.JLabel motherBoardMakersHp;
    private javax.swing.JLabel powerSourceMakersApple;
    private javax.swing.JLabel powerSourceMakersApple1;
    private javax.swing.JLabel powerSourceMakersApple2;
    private javax.swing.JLabel powerSourceMakersHp;
    private javax.swing.JLabel ramMakersApple;
    private javax.swing.JLabel ramMakersHp;
    private javax.swing.JButton removeAssembler1;
    private javax.swing.JButton removeAssembler2;
    private javax.swing.JButton removeCpu1;
    private javax.swing.JButton removeCpu2;
    private javax.swing.JButton removeCpu3;
    private javax.swing.JButton removeDay;
    private javax.swing.JButton removeDeadline;
    private javax.swing.JButton removeGraphCard1;
    private javax.swing.JButton removeGraphCard2;
    private javax.swing.JButton removeMB2;
    private javax.swing.JButton removeMB3;
    private javax.swing.JButton removeMotherBoard1;
    private javax.swing.JButton removePowSour1;
    private javax.swing.JButton removePowSour2;
    private javax.swing.JButton removePowSour3;
    private javax.swing.JButton removeRam1;
    private javax.swing.JButton removeRam2;
    private javax.swing.JButton removeRam3;
    private javax.swing.JButton txt;
    // End of variables declaration//GEN-END:variables
}
